local vars = require("variables")

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("caelestia shell -d")
    -- hl.exec_cmd("hyprpaper")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("[workspace 1 silent] " .. vars.browser)
    hl.exec_cmd("[workspace 6 silent] vesktop")
    hl.exec_cmd("zapzap --daemon")
    hl.exec_cmd("input-remapper-control --command autoload")
    hl.exec_cmd("[workspace 6 silent] " .. vars.terminal)
    hl.exec_cmd("easyeffects --gapplication-service")
end)
