-- Hyprland Lua config.

hl.config({
    autogenerated = false,
})

require("variables")
require("scheme.current")
require("monitors")
require("env")
require("autoexec")
require("general")
require("layouts")
require("input")
require("keybinds")
require("windowrules")
require("permissions")
