##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# First monitor
workspace = 1, monitor:DP-1, default:true, layout:dwindle

# Second monitor
workspace = 6, monitor:HDMI-A-1, default:true, layout:dwindle

windowrule {
    name = kitty_tile_rule
    match:class = ^(kitty)$
    tile = on
}

$games = ^(steam_app_.*|lutris-game_class|minigalaxy|playnite_game_class|gamescope|steam|prism-launcher|.*[Ww]ine.*)$
windowrule {
  name = gaming_workspace_rule
  match:class = $games
  workspace = special:gaming
  content = game
  no_anim = on
  no_blur = on
  no_shadow = on
  fullscreen = on
  rounding = 0
  immediate = on
  border_size = 0
  monitor = DP-1
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = maximize_rule
  suppress_event = maximize
  match:class = .*
}

# Fix dragging issues
windowrule {
  name = dragging_rule
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# No animation for rofi
layerrule {
    name = rofi_no_anim_rule
    no_anim = on
    match:class = ^(rofi)$
}